[package]
name = "goree"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
goreecloud-containers-core = { path = "../goreecloud-containers-core" }
goreecloud-containers-runtime = { path = "../goreecloud-containers-runtime" }

[lints]
workspace = true
